spring:
  application:
    name: bankCards

  datasource:
    url: jdbc:postgresql://localhost:5432/bankcardsdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false

logging:
  level:
    org.springframework: DEBUG

server:
  port: 8080
