spring:
  application:
    name: bankCards

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/bankcardsdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false

logging:
  level:
    org.springframework: TRACE

server:
  port: 8080

springdoc:
  swagger-ui:
    url: /openapi.yaml
jwt:
  signing:
    key: "aL9xvZ1kT7qMwE5YcBnRpHsF3gLdUJXeQvCtAi82sNhObKrz"
